#sonar.host.url=https://sonarcloud.io
sonar.organization=ministryofjustice
sonar.projectKey=ministryofjustice_hmpps-probation-supervision-early-termination-ui
sonar.javascript.lcov.reportPaths=test_results/jest/lcov.info,coverage/lcov.info
sonar.sources=server
sonar.exclusions=server/views/_components/govuk/**,**/*.test.ts,server/controllers/*.test.ts,**/*.cy.ts,**/testutils/*,**/app.ts,**/mocks/*
sonar.coverage.exclusions=**/*.test.ts,**/*.cy.ts,server/@types/**,server/index.ts,server/sentry.ts,server/data/index.ts,server/data/model/featureFlags.ts
